DROP TABLE IF EXISTS order_ratings CASCADE;

CREATE TABLE order_ratings (
  id SERIAL PRIMARY KEY NOT NULL,
  satisfication BOOLEAN NOT NULL,
  message TEXT,
  dish_id INT NOT NULL REFERENCES dishes(id) ON DELETE CASCADE,
  order_id INT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  customer_id INT NOT NULL REFERENCES customers(id) ON DELETE CASCADE
);